# action.yml
name: 'Qubic Contract Verify'
description: 'Run the Qubic contract verification tool on an input file'
inputs:
  filepath: # id of input
    description: 'Input file to verify'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filepath }}
