# action.yml
name: 'Qubic Contract Verify'
description: 'Run the Qubic contract verification tool on an input file'
inputs:
  filepaths: # id of input
    description: 'Input file(s) to verify, comma separated'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filepaths }}
