name: 'Qubic Contract Verify'
description: 'Run the Qubic contract verification tool on one or multiple files'
branding:
  icon: 'check-square'
  color: 'blue'

inputs:
  filepaths:
    description: 'Input file(s) to verify, comma separated (no spaces)'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.filepaths }}
